server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ravjan07/config-repo
          cloneOnStart: false
          refreshRate: 0
          basedir: ${user.home}//config-repo-basedir

